title = "Cole Fuerth"
baseURL = "https://colefuerth.github.io/"
theme = "resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
# address = ""
email = "colefuerth@gmail.com"
favicon = "/favicon.ico"
firstName = "Cole"
lastName = "Fuerth"
phone = "1-519-300-2877"
profileImage = "img/cole.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = true
showQr = false
showSkills = true
showCertifications = false

# [params.google]

# [params.google.analytics]
# trackerID = "4809327005"

[[params.handles]]
link = "https://github.com/colefuerth/"
name = "GitHub"

[[params.handles]]
link = "https://www.linkedin.com/in/cole-fuerth-48344520a/"
name = "LinkedIn"

[[params.handles]]
link = "https://www.instagram.com/cole_on_a_cob/"
name = "Instagram"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"